app_auth/urls.py
from django.urls import path
from .views import login_blog, register
from .views import logout_blog

urlpatterns = [
    path('login',login_blog,name="login-blog"),
    path('logout',logout_blog,name="logout_blog"),
    path('register',register,name="register")
]

blog/urls.py
from typing import ValuesView
from django.urls import path

from . import views

urlpatterns = [
    path("",views.home, name="home")
]

myblog/urls.py
import blog
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

from blog.views import home
from blog.views import details
from blog.views import search

urlpatterns = [
    path('admin/', admin.site.urls,name="admin"),
    path('', home, name= "home"), #path('', include("blog.urls")),
    path('article/<int:id>', details, name="details"),
    path('recherche', search, name="search"),
    path('auth/', include("app_auth.urls")),
    path('app-admin/', include("app_admin.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app_auth/forms.py
from django import forms
from django.forms import widgets
from django.forms.models import ModelForm
from django.views.generic.edit import UpdateView
from blog.models import Article

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    pwd = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    
class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    pwd = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    pwd_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    
class ArticleForm (forms.ModelForm):
    class Meta:
        model= Article
        fields= ['title','categorie','desc','image']
        labels= {'title':'Titre','categorie': 'Categorie','desc':'Description','image':'Image',     'title':'Titre','categorie': 'Categorie','desc':'Description','image':'Image'}
        widgets={
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'categorie': forms.Select(attrs={'class': 'form-control'}),
            'desc': forms.Textarea(attrs={'class':'form-control','rows':5}),
            #'image':forms.ImageField()
        }

app_auth/views.py
from django import forms
import django
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import *



def logout_blog(request):
        logout(request)
        return redirect("home")# Redirect to a success page.
    


#la fonction ci est executée quand on clique sur le formulaire
def login_blog(request):
    if request.method == "POST": #si l'utilisateur clique sur se connecter
        form = LoginForm(request.POST)
        #POST={'username':'toto', 'pwd':'password'}
        if form.is_valid():
            username= form.cleaned_data['username']
            pwd= form.cleaned_data['pwd']
            user= authenticate(username=username,password=pwd)
            if user is not None:
                login(request,user)#Cette fonction permet de stocker l'utilisateur qui s'est connecté dans l'objet request
                return redirect("home")
            else:
                messages.error(request,"! Erreur d'authentification: nom d'utilisateur ou mot de passe incorect")
                return render(request, "login2.html",{'form':form}) 
        else :
            #messages.error(request,"! Erreur d'authentification: nom d'utilisateur ou mot de passe incorect")
            for field in form.errors:
                form[field].field.widget.attrs['class'] += ' is-invalid'#widget permet d'attribuer des classes à des balises html
            return render(request, "login2.html",{'form':form}) 
    else:
        
        form=LoginForm()
        return render(request,"login2.html",{"form":form})
    
def register(request):
    if request.method == 'POST':
        form= RegisterForm(request.POST)
        if form.is_valid():
            username= form.cleaned_data['username']
            pwd= form.cleaned_data['pwd']
            email=form.cleaned_data['email']
            pwd_confirm= form.cleaned_data['pwd_confirm']
            if pwd == pwd_confirm:
                user = User.objects.create_user( username=username,email=email, password=pwd)
                if user is not None:
                    return redirect('login-blog')
                else:
                    print("Erreur de création de compte")
                    msg="Erreur de création de compte"
                    #messages.error(request,"Erreur de création de compte")
                    return render(request,'register.html',{"form":form,"msg":msg})
            else:
                msg="Les mots de passe ne sont pas identiques"
                print("Les mots de passe ne sont pas identiques")
                #messages.error(request,"Les mots de passe ne sont pas identiques")
                return render(request,'register.html',{"form":form,"msg":msg})
        else:
            for field in form.errors:
                form[field].field.widget.attrs['class'] += ' is-invalid'
            return render(request, "register.html",{'form':form}) 
    else:
        form= RegisterForm()
        return render(request,'register.html',{"form":form})   
    
    
    
    
    
    
    
    
    
    """
    if request.method== "POST":
        username=request.POST["username"]
        pwd=request.POST["pwd"]
        user=authenticate(username=username,password=pwd)
        if user is not None:
           return redirect("home")
        else:
            messages.error(request,"Erreur d'authentification")
            return render(request, "login.html") 
        
        
    return render(request,"login.html")
    """

app_auth/templates/login.html
{% extends "base2.html" %} 

{% block title %}Connexion au blog{% endblock %} 

{%block content %}

    <div class="container">
        <div class="col-md-12 mt-5 p-5">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger"><strong>{{message}}</strong></div>
            {% endfor %}
            {% endif %}
            <form action="" method="POST">{% csrf_token %}
                <div class="card">
                    <div class="card-header text-center"><i class="fas fa-user"></i>Connexion au blog </div>
                    <div class="card-body">
                        <input  type="text" placeholder="Nom utilisateur" name="username" class="form-control"/><br />
                        <input  type="password" placeholder="Mot de passe" name="pwd" class="form-control"/>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-primary btn-block">Se connecter</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

app_auth/templates/login2.html
{% extends "base2.html" %} 

{% block title %}Connexion au blog{% endblock %} 

{%block content %}

    <div class="container">
        <div class="col-md-12 mt-5 p-5">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-danger text-center"><strong>{{message}}</strong></div>
                {% endfor %}
            {% endif %}
            {% if msg %}
            <div class="alert alert-success" role="alert">
                {{msg}}
              </div>
            {% endif %}
            <form action="" method="POST" novalidate>{% csrf_token %}
                <div class="card">
                    <div class="card-header text-center"><i class="fas fa-user"></i>Connexion au blog </div>
                    <div class="card-body">
                        <label for="id_username">Nom Utilisateur</label>
                        {% if form.username.errors %}
                            {% for error in form.username.errors %}
                            <div>
                                <small class="text-danger" style="font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif; font-weight: 700">{{error}}</small>
                            </div>
                            {% endfor %} 
                        {% endif %}
                        {{form.username}}
                        <label for="id_pwd">Mot de Passe</label>
                        {% if form.pwd.errors %}
                            {% for error in form.pwd.errors %}
                            <div>
                                <small class="text-danger" style="font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif; font-weight: 700">{{error}}</small>
                            </div>
                            {% endfor %}
                        {% endif %}
                        {{form.pwd}}
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-primary btn-block">Se connecter</button>
                    </div>
                </div>
                <div class="text-center">
                    Vous n'avez pas encore de compte? <a href={% url 'register' %}>Créer Votre Compte</a>
                </div>
                
            </form>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function(){
            $('input').keyup(function(){
                let textSaisi= $(this).val();
                if(textSaisi === ""){
                    if(!$(this).hasClass('is-invalid')){
                        $(this).addClass('is-invalid')
                    }
                }else{
                    $(this).removeClass('is-invalid');
                }
                
            })
        })
    </script>
{% endblock %}

app_auth/templates/register.html
{% extends 'base.html' %}



{% block title %}Création utilisateur{% endblock %} 

{%block content %}
<h1 class="text-center mt-5">Création de compte Utilisateur</h1>
<div class="container">
    {% if msg %}
        <div class="alert alert-danger text-center" role="alert" style="font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif; font-weight: 700">
            {{msg}}
        </div>
        <!--        
        <div>
            <small class="text-danger" style="font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif; font-weight: 700">{{msg}}</small>
        </div>
         --> 

    {% endif %}
    <form action="" method="POST"> {% csrf_token %}
        <label for="id_username">Nom Utilisateur</label>
        {{form.username}}

        <label for="id_email">Email</label>
        {{form.email}}

        <br>
        <label for="id_pwd">Mot de Passe</label>
        {{form.pwd}}

        <br>
        <label for="id_pwd_confirm">Confirmation de Mot de Passe</label>
        {{form.pwd_confirm}}

        <br>
        <button class="btn btn-primary btn-block mb-5"><i class="fas fa-user-plus"></i>&nbsp; Créer</button>
    </form>
</div>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function(){
            $('input').keyup(function(){
                let textSaisi= $(this).val();
                if(textSaisi === ""){
                    if(!$(this).hasClass('is-invalid')){
                        $(this).addClass('is-invalid')
                    }
                }else{
                    $(this).removeClass('is-invalid');
                }
                
            })
        })
    </script>
{% endblock %}